In [21]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import RobustScaler

# Pre-processing the Data

house_df = pd.read_csv("house_price_dataset_handled.csv")
X = house_df.drop('price', axis=1)  # Features
y = house_df['price']  # Target variable

# Splitting the data for testing and training

X_train , X_test , y_train , y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

#Scaling the Features

scaler = RobustScaler()

X_train.iloc[:, 1:] = scaler.fit_transform(X_train.iloc[:, 1:])  # Only scale the features, exclude X0
X_test.iloc[:, 1:] = scaler.transform(X_test.iloc[:, 1:])  # Same for test data

# Converting to Numpy Array
if isinstance(X_train, pd.DataFrame):
    X_train = X_train.to_numpy()
if isinstance(X_test, pd.DataFrame):
    X_test = X_test.to_numpy()  


In [22]:
# Funtions

def compute_gradient(theta, X, y):
    m = len(y)
    predictions = np.dot(X, theta)
    errors = predictions - y
    gradient = (1/m) * np.dot(X.T, errors)
    return gradient

def cost_function(y_pred, y_test_or_train):
    m = len(y_pred)
    sum = 0
    y = y_test_or_train.to_numpy()
    for i in range(m):
        sum += ( y_pred[i] - y[i] )**2
    return ( 1 / (2 * m) ) * sum

def batch_gradient_descent(theta, X_train, y_train, lr):
    m = len(y_train)
    y_train = y_train.to_numpy()  # Ensure y_train is a NumPy array
    y_pred = np.dot(X_train, theta)  # Predictions

    for j in range(len(theta)):  # Iterate over all parameters (features)
        sum_grad = 0
        for i in range(m):  # Iterate over all data points
            # Correct the gradient: (y_pred - y_train) instead of (y_train - y_pred)
            sum_grad += (y_pred[i] - y_train[i]) * X_train[i, j]
        theta[j] = theta[j] - (lr * sum_grad) / m  # Update theta[j]
    
    return theta

In [14]:
# Training the model

theta = np.random.randn(X_train.shape[1]) * 0.01

tolerance = 1e-6 # Convergence thershold
previous_cost = float('inf')
alpha = 0.2
iteration = 0
cost_history = []
theta_history = []

while True:

    if iteration >= 10000:
        break
    
    y_pred = np.dot(X_train , theta)  
    cost = cost_function(y_pred, y_train)
    print(cost)
    
    if abs(previous_cost - cost) < tolerance:  
        break  

    theta = batch_gradient_descent(theta, X_train, y_train, alpha)  
    previous_cost = cost  
    iteration += 1

    if iteration % 100 == 0:  
       cost_history.append(cost)
       theta_history.append(theta.copy())
print("Converged in ",iteration," iterations")



242359262865.488
168185754733.9417
128766716729.44815
107274602660.87485
95166423058.10692
88059652967.08272
83678742497.28418
80825406591.19029
78858115615.80727
77426586934.41861
76334976868.3723
75470600176.13087
74766338184.5432
74180551186.16145
73686190052.92065
73264801230.70296
72903168010.18843
72591391141.00975
72321766415.14282
72088110221.1817
71885341087.6272
71709210261.9227
71556120959.00957
71423001734.65643
71307213914.73035
71206481219.55592
71118834430.729
71042566681.67815
70976196562.4399
70918437191.2274
70868169991.49806
70824422278.56973
70786347993.85968
70753211079.76176
70724371094.4529
70699270741.78099
70677425047.5673
70658411956.81584
70641864160.46046
70627461988.01494
70614927225.4037
70604017736.54788
70594522783.5971
70586258954.70763
70579066620.27649
70572806848.93033
70567358723.5545
70562617005.40895
70558490101.18575
70554898293.68524
70551772201.92331
70549051440.91547
70546683455.24124
70544622503.85277
70542828776.51564
70541267624.81424
70539

In [23]:
# Hyperparameters for Adam
alpha = 0.01          # Initial learning rate
beta1 = 0.9           # Exponential decay rate for momentum
beta2 = 0.999         # Exponential decay rate for RMS
epsilon = 1e-8        # Small number to avoid division by zero

# Initialize variables
theta = np.random.randn(X_train.shape[1]) * 0.01
m_t = np.zeros_like(theta)   # First moment
v_t = np.zeros_like(theta)   # Second moment
t = 0                        # Time step

tolerance = 1e-6
previous_cost = float('inf')
iteration = 0
cost_history = []
theta_history = []

while iteration < 10000:
    t += 1
    iteration += 1

    # Compute cost and gradient
    y_pred = np.dot(X_train, theta)
    cost = cost_function(y_pred, y_train)

    if abs(previous_cost - cost) < tolerance:
        break

    grad = compute_gradient(theta, X_train, y_train)

    # Adam update
    m_t = beta1 * m_t + (1 - beta1) * grad
    v_t = beta2 * v_t + (1 - beta2) * (grad ** 2)

    m_hat = m_t / (1 - beta1 ** t)
    v_hat = v_t / (1 - beta2 ** t)

    theta = theta - alpha * m_hat / (np.sqrt(v_hat) + epsilon)

    previous_cost = cost

    if iteration % 100 == 0:
        cost_history.append(cost)
        theta_history.append(theta.copy())

print("Converged in", iteration, "iterations")


Converged in 10000 iterations


In [24]:
cost_history

[242358252073.6838,
 242357241637.11407,
 242356231207.08914,
 242355220783.5327,
 242354210366.37195,
 242353199955.5347,
 242352189550.9492,
 242351179152.5418,
 242350168760.24487,
 242349158373.98877,
 242348147993.70233,
 242347137619.32288,
 242346127250.78146,
 242345116888.01834,
 242344106530.96844,
 242343096179.57254,
 242342085833.77032,
 242341075493.5061,
 242340065158.72382,
 242339054829.37234,
 242338044505.39752,
 242337034186.75052,
 242336023873.38287,
 242335013565.25092,
 242334003262.30814,
 242332992964.5136,
 242331982671.82867,
 242330972384.21262,
 242329962101.6286,
 242328951824.04337,
 242327941551.4226,
 242326931283.7357,
 242325921020.95142,
 242324910763.04205,
 242323900509.98203,
 242322890261.74496,
 242321880018.3074,
 242320869779.64536,
 242319859545.7394,
 242318849316.56885,
 242317839092.11383,
 242316828872.3593,
 242315818657.28583,
 242314808446.87845,
 242313798241.125,
 242312788040.00943,
 242311777843.51993,
 242310767651.64432,
 242309

In [25]:
theta_history

[array([0.99420399, 1.00862488, 1.00288819]),
 array([1.99420252, 2.00862136, 2.00288139]),
 array([2.99419998, 3.00861528, 3.00286962]),
 array([3.9941964 , 4.00860672, 4.00285306]),
 array([4.99419183, 5.00859577, 5.00283188]),
 array([5.99418629, 6.00858253, 6.00280625]),
 array([6.99417983, 7.00856707, 7.00277635]),
 array([7.99417248, 8.0085495 , 8.00274235]),
 array([8.99416429, 9.00852989, 9.00270441]),
 array([ 9.99415527, 10.00850833, 10.0026627 ]),
 array([10.99414548, 11.00848491, 11.00261739]),
 array([11.99413495, 12.00845971, 12.00256862]),
 array([12.9941237 , 13.00843281, 13.00251657]),
 array([13.99411177, 14.00840428, 14.00246137]),
 array([14.9940992 , 15.00837421, 15.00240318]),
 array([15.99408602, 16.00834266, 16.00234215]),
 array([16.99407224, 17.00830972, 17.0022784 ]),
 array([17.99405792, 18.00827544, 18.00221209]),
 array([18.99404306, 19.00823991, 19.00214334]),
 array([19.99402771, 20.00820318, 20.00207227]),
 array([20.99401188, 21.00816532, 21.00199902])

In [26]:
print("theta = ",theta)

theta =  [ 99.99230331 100.00407765  99.99408818]


In [27]:
y_predictions = np.dot(X_test , theta)

In [28]:
# Evaluation Functions

def mean_absolute_error(y_pred , y_test_or_train):
    m = len(y_pred)
    sum = 0
    y = y_test_or_train.values
    for i in range(m):
        sum += np.abs( y_pred[i] - y[i] )
    return (1/m) * sum

def mean_squared_error(y_pred, y_test_or_train):
    m = len(y_pred)
    sum = 0
    y = y_test_or_train.values
    for i in range(m):
        sum += ( y_pred[i] - y[i] )**2
    return ( 1 / m ) * sum

def r2_score(y_pred , y_test_or_train):
    numerator = 0
    denominator = 0
    sum = 0
    m = len(y_pred)
    y = y_test_or_train.values

    for i in range(m):
        sum += y[i]
        numerator += (y_pred[i] - y[i])**2
    mean = sum/m

    for i in range(m):
        denominator += (y[i] - mean)**2
    
    return 1 - (numerator/denominator)

def root_mean_squared_error(mse):
    return mse**0.5

In [29]:
# Testing the model

print(f"Cost : ", cost_function(y_predictions,y_test))
print(f"Mean squared error : ", mean_squared_error(y_predictions,y_test))
print(f"Root mean squared error : ", root_mean_squared_error(mean_squared_error(y_predictions,y_test)))
print(f"Mean absolute error : ", mean_absolute_error(y_predictions,y_test))
print(f"R2 score : ", r2_score(y_predictions,y_train))
print(f"These are the model predictions : ", y_predictions)

Cost :  607235269988.6737
Mean squared error :  1214470539977.3474
Root mean squared error :  1102030.1901387945
Mean absolute error :  581148.1146391944
R2 score :  -1.6093588376117571
These are the model predictions :  [ 3.33295779e+01  1.99986391e+02  1.66665018e+02  3.33295779e+01
  2.33327744e+02  1.33323666e+02 -6.66744998e+01  5.99982723e+02
  1.33323666e+02 -6.66645103e+01  9.99923033e+01  2.33317754e+02
  2.66659106e+02  2.33327744e+02  2.33327744e+02  2.33327744e+02
  2.33327744e+02  3.33295779e+01 -1.78486819e-03  9.99923033e+01
  4.33335899e+02  3.66653195e+02  1.66665018e+02  3.33295779e+01
  1.33323666e+02  9.99923033e+01  6.66609406e+01  6.66609406e+01
 -1.66668588e+02  9.99923033e+01  4.33325910e+02  3.66653195e+02
 -1.78486819e-03 -1.66668588e+02  1.33333656e+02 -6.66645103e+01
  3.33295779e+01  3.33295779e+01  3.33321832e+02  1.33323666e+02
  3.99994547e+02  3.33295779e+01  1.33323666e+02  3.33295779e+01
  2.33317754e+02  2.33327744e+02  3.33331821e+02 -1.66668588e+02